.TH TOPIC_PUBLISHER_SUBSCRIBE 2 "March 25, 2017" "IIT - CS551" "Syscalls Manual"

.SH NAME
topic_publisher_subscribe \- register a process to publish messages in a topic.

.SH SYNOPSIS
.nf
.ft B
#include <topic.h>

int topic_publisher_subscribe(topicid_t id)
.ft R
.fi
.SH DESCRIPTION
.de SP
.if t .sp 0.4
.if n .sp
..
.B topic_publisher_subscribe()
allows a process to add itself from the publisher list of a topic. If the specified topic \fBid\fP doesn't exist, it returns an error. 

.SH "RETURN VALUE
On success, zero is returned. Otherwise, a value of \-1 is returned, and the global variable errno is set to indicate the error.

.SH ERRORS
.TP 15
.B ENOENT
The specified topic \fBid\fP doesn't exist.
.TP 15
.B EALREADY
The process is already registered in this topic.
.TP 15
.B ENOMEM
Not enough memory to create a new publisher.

.SH "SEE ALSO"
.BR topic_lookup (2)
.BR topic_create (2),
.BR topic_publisher_unsubscribe (2),
.BR topic_client_subscribe (2),
.BR topic_client_unsubscribe (2),
.BR topic_publish (2),
.BR topic_retrieve (2).
