.TH TOPIC_LOOKUP 2 "March 25, 2017" "IIT - CS551" "Syscalls Manual"

.SH NAME
topic_lookup \- discover the list of existing topics

.SH SYNOPSIS
.nf
.ft B
#include <topic.h>

int topic_lookup(topicid_t topic_ids[], size_t count)
.ft R
.fi
.SH DESCRIPTION
.de SP
.if t .sp 0.4
.if n .sp
..
.B topic_lookup()
allows a process to discover what topics there are. The list of existing topic IDs is returned in the provided array \fBtopic_ids\fP of size \fBcount\fP.

.SH "RETURN VALUE
On success, the number of existing topics is returned and \fBtopic_ids\fP contains the topic IDs. Otherwise, a value of \-1 is returned, and the global variable \fBerrno\fP is set to indicate the error.

.SH ERRORS
.TP 15
.B ERANGE
The provided array is too small.
.TP 15
.B EGENERIC
Any other error.

.SH "SEE ALSO"
.BR topic_create (2)
.BR topic_publisher_subscribe (2),
.BR topic_publisher_unsubscribe (2),
.BR topic_client_subscribe (2),
.BR topic_client_unsubscribe (2),
.BR topic_publish (2),
.BR topic_retrieve (2).
