.TH TOPIC_PUBLISH 2 "March 25, 2017" "IIT - CS551" "Syscalls Manual"

.SH NAME
topic_publish - publish a message in a topic.

.SH SYNOPSIS
.nf
.ft B
#include <topic.h>

int topic_publish(topicid_t id, void *buf, size_t count)
.ft R
.fi
.SH DESCRIPTION
.de SP
.if t .sp 0.4
.if n .sp
..
.B topic_publish()
allows a process to send a message to a topic. The message consists in the first \fBcount\fp bytes of buffer \fBbuf\fP.

.SH "RETURN VALUE
On success, zero is returned. Otherwise, a value of \-1 is returned, and the global variable errno is set to indicate the error.

.SH ERRORS
.TP 15
.B ENOENT
The specified topic \fBid\fP doesn't exist.
.TP 15
.B ENOBUFS
The maximum number of stored messages is reached.
.TP 15
.B EACCES
The process is not registered as a publisher.
.TP 15
.B EINVAL
The \fBcount\fP is equal to zero.
.TP 15
.B ENOMEM
Not enough memory to create a new message.
.TP 15
.B EGENERIC
Any other error.

.SH "SEE ALSO"
.BR topic_lookup (2)
.BR topic_create (2),
.BR topic_publisher_subscribe (2),
.BR topic_publisher_unsubscribe (2),
.BR topic_client_subscribe (2),
.BR topic_client_unsubscribe (2),
.BR topic_retrieve (2).
