.TH TOPIC_RETRIEVE 2 "March 25, 2017" "IIT - CS551" "Syscalls Manual"
.SH NAME
topic_retrieve - retrieve a message from a topic.

.SH SYNOPSIS
.nf
.ft B
#include <topic.h>

int topic_retrieve(topicid_t id, void **buf)
.ft R
.fi
.SH DESCRIPTION
.de SP
.if t .sp 0.4
.if n .sp
..
.B topic_retrieve()
allows a process to retrieve a message from a topic.
The returned buffer is allocated by the function.
The caller should free(3) the returned buffer.

.SH "RETURN VALUE
On success, \fBbuf\fp is set to an allocated buffer containing a message, and the function returns the size of the message. Otherwise, a value of \-1 is returned, and the global variable errno is set to indicate the error.

.SH ERRORS
.TP 15
.B ENOENT
The specified topic \fBid\fP doesn't exist.
.TP 15
.B EACCES
The process is not registered to retrieve messages from this topic.
.TP 15
.B ENOMSG
There is no messages for this user.
.TP 15
.B EGENERIC
Any other error.
	
.SH "SEE ALSO"
.BR topic_lookup (2)
.BR topic_create (2),
.BR topic_publisher_subscribe (2),
.BR topic_publisher_unsubscribe (2),
.BR topic_client_subscribe (2),
.BR topic_client_unsubscribe (2),
.BR topic_publish (2).
