.TH TOPIC_CREATE 2 "March 25, 2017" "IIT - CS551" "Syscalls Manual"

.SH NAME
topic_create \- create a new topic

.SH SYNOPSIS
.nf
.ft B
#include <topic.h>

int topic_create(topicid_t id)
.ft R
.fi
.SH DESCRIPTION
.de SP
.if t .sp 0.4
.if n .sp
..
.B topic_create()
allows a process to create a topic named \fBid\fP. If a topic with the same \fBid\fP already exists, it returns an error.

.SH "RETURN VALUE
On success, zero is returned. Otherwise, a value of \-1 is returned, and the global variable \fBerrno\fP is set to indicate the error.

.SH ERRORS
.TP 15
.B EALREADY
A topic with same \fBid\fP already exists.
.TP 15
.B ENOMEM
Not enough memory to create a new topic.

.SH "SEE ALSO"
.BR topic_lookup (2)
.BR topic_publisher_subscribe (2),
.BR topic_publisher_unsubscribe (2),
.BR topic_client_subscribe (2),
.BR topic_client_unsubscribe (2),
.BR topic_publish (2),
.BR topic_retrieve (2).
